services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres  # Changed from admin to postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DataWarehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # REMOVE THIS LINE: - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data: